
version: "3.9"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  api:
    build: ./apps/api
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/budgiehero
      - FRONTEND_ORIGIN=http://localhost:4200
      - JWT_SECRET=dev_secret_change_me
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - OIDC_REDIRECT_URI=http://localhost:3000/auth/google/callback
      - REDIS_URL=redis://redis:6379
    ports: ["3000:3000"]
    depends_on: [mongo, redis]
  worker:
    build: ./apps/worker
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/budgiehero
      - REDIS_URL=redis://redis:6379
    depends_on: [mongo, redis]
volumes:
  mongo_data:
