# render.yaml — BudgieHero (Test + Prod + EnvVarGroups)

envVarGroups:
  - name: budgiehero-secrets-test
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OIDC_REDIRECT_URI
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://budgiehero-web-test.vercel.app

  - name: budgiehero-secrets-prod
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OIDC_REDIRECT_URI
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://budgiehero.app

services:
  # ========== TEST ==========
  - name: budgiehero-redis-test
    type: redis
    plan: starter
    region: frankfurt
    # ▼ Vereist door blueprint schema voor Key Value
    ipAllowList: []         # Alleen interne verbindingen; extern = geblokkeerd  [1](https://www.mongodb.com/docs/atlas/billing/serverless-instance-costs/)[2](https://vercel.com/pricing)

  - name: budgiehero-api-test
    type: web
    runtime: docker
    rootDir: apps/api
    region: frankfurt
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: budgiehero-secrets-test
      - key: REDIS_URL
        fromService:
          type: redis
          name: budgiehero-redis-test
          property: connectionString

  - name: budgiehero-worker-test
    type: worker
    runtime: docker
    rootDir: apps/worker
    region: frankfurt
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: budgiehero-secrets-test
      - key: REDIS_URL
        fromService:
          type: redis
          name: budgiehero-redis-test
          property: connectionString

  # ========== PROD ==========
  - name: budgiehero-redis-prod
    type: redis
    plan: standard
    region: frankfurt
    # ▼ Vereist: specificeer allow list; leeg = intern‑only
    ipAllowList: []         # Verhoog veiligheid; extern alleen indien nodig      [1](https://www.mongodb.com/docs/atlas/billing/serverless-instance-costs/)

  - name: budgiehero-api-prod
    type: web
    runtime: docker
    rootDir: apps/api
    region: frankfurt
    plan: standard
    healthCheckPath: /health
    # Zet autodeploy UIT in de service-instellingen; Prod via Deploy Hook/handmatig  [3](https://rebusfarm.net/blog/top-five-render-farms)
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: budgiehero-secrets-prod
      - key: REDIS_URL
        fromService:
          type: redis
          name: budgiehero-redis-prod
          property: connectionString

  - name: budgiehero-worker-prod
    type: worker
    runtime: docker
    rootDir: apps/worker
    region: frankfurt
    plan: standard
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: budgiehero-secrets-prod
      - key: REDIS_URL
        fromService:
          type: redis
          name: budgiehero-redis-prod
          property: connectionString