services:
  # === AUTH SERVICE ===
  - type: web
    name: auth-service-test
    env: node
    plan: free
    region: frankfurt
    branch: develop
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://budgiehero_user:NczvUblCuPjcASwH@cluster0.ljvd4r7.mongodb.net/budgiehero/auth-test?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: test_secret_key
    autoDeploy: true
    healthCheckPath: /auth/login

  - type: web
    name: auth-service-prod
    env: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://budgiehero_user:NczvUblCuPjcASwH@cluster0.ljvd4r7.mongodb.net/budgiehero/auth?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: prod_secret_key
    autoDeploy: true
    healthCheckPath: /auth/login

  # === BUDGET SERVICE ===
  - type: web
    name: budget-service-test
    env: node
    plan: free
    region: frankfurt
    branch: develop
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        value: mongodb+srv://budgiehero_user:NczvUblCuPjcASwH@cluster0.ljvd4r7.mongodb.net/budgiehero/budget-test?retryWrites=true&w=majority&appName=Cluster0
    autoDeploy: true
    healthCheckPath: /budget/health

  - type: web
    name: budget-service-prod
    env: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 5001
      - key: MONGO_URI
        value: mongodb+srv://budgiehero_user:NczvUblCuPjcASwH@cluster0.ljvd4r7.mongodb.net/budgiehero/budget?retryWrites=true&w=majority&appName=Cluster0
    autoDeploy: true
    healthCheckPath: /budget/health

  # === TRANSACTION SERVICE ===
  - type: web
    name: transaction-service-test
    env: node
    plan: free
    region: frankfurt
    branch: develop
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 5002
      - key: MONGO_URI
        value: mongodb+srv://budgiehero_user:NczvUblCuPjcASwH@cluster0.ljvd4r7.mongodb.net/budgiehero/transaction-test?retryWrites=true&w=majority&appName=Cluster0
   