# render.yaml — BudgieHero (Gratis setup: Web + Key Value, Test & Prod)

# -------------------------
# EnvVarGroups per omgeving
# -------------------------
envVarGroups:
  - name: budgiehero-secrets-test
    envVars:
      # App / OAuth
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OIDC_REDIRECT_URI
        sync: false
      # Data: Mongo Atlas (extern, free tier) of straks Postgres
      - key: MONGODB_URI
        sync: false
      # Frontend URL (Test)
      - key: FRONTEND_ORIGIN
        value: https://budgiehero-web-test.vercel.app

  - name: budgiehero-secrets-prod
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: OIDC_REDIRECT_URI
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_ORIGIN
        value: https://budgiehero.app

# --------------
# Services (T+P)
# --------------
services:
  # ======= TEST (gratis) =======
  - name: budgiehero-redis-test
    type: redis
    plan: free                  # GRATIS Key Value instance
    region: frankfurt
    ipAllowList: []             # intern-only (vereist door schema)  # ← veilig en gratis
  - name: budgiehero-api-test
    type: web
    runtime: docker
    rootDir: apps/api
    region: frankfurt
    plan: free                  # GRATIS Web Service
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: budgiehero-secrets-test
      - key: REDIS_URL
        fromService:
          type: redis
          name: budgiehero-redis-test
          property: connectionString

  # ======= PROD (gratis) =======
  - name: budgiehero-redis-prod
    type: redis
    plan: free
    region: frankfurt
    ipAllowList: []             # intern-only
  - name: budgiehero-api-prod
    type: web
    runtime: docker
    rootDir: apps/api
    region: frankfurt
    plan: free
    healthCheckPath: /health
    # Zet autodeploy UIT in de service-instellingen als je production niet automatisch wilt.
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: budgiehero-secrets-prod
      - key: REDIS_URL
        fromService:
          type: redis
          name: budgiehero-redis-prod
          property: connectionString